pub mod acp;
pub mod agents;
pub mod commands;
pub mod index;
pub mod prompt;
pub mod provider;
pub mod settings;
pub mod updates;

pub use acp::RuntimeOptions as AcpRuntimeOptions;
pub use acp::run_http as run_acp_http;
pub use acp::run_stdio as run_acp_stdio;
pub use agents::AgentProfile;
pub use agents::AgentRunContext;
pub use agents::AgentRunLogRecord;
pub use agents::AgentRunRecord;
pub use agents::AgentRunStatus;
pub use agents::AgentStore;
pub use agents::serialize_agent_log_record;
pub use agents::slug_for_name;
pub use commands::CommandContext;
pub use commands::CommandDescriptor;
pub use commands::CommandRegistry;
pub use commands::CommandResult;
pub use commands::register_defaults as register_default_commands;
pub use index::builder::BuildOptions;
pub use index::events::IndexEvent;
pub use index::events::IndexSummary;
pub use index::query::QueryHit;
pub use index::query::QueryResponse;
pub use index::query::query_index;
pub use prompt::apply_overlay_to_config;
pub use prompt::default_base_prompt;
pub use prompt::default_prompt_path;
pub use prompt::global_prompt;
pub use prompt::global_prompt_sources;
pub use prompt::init_global_from_settings as init_global_prompt;
pub use prompt::overlay_from_settings;
pub use provider::DEFAULT_OLLAMA_ENDPOINT;
pub use provider::OSS_PROVIDER_ID;
pub use provider::custom_provider_model_info;
pub use provider::custom_providers;
pub use provider::fetch_custom_provider_models;
pub use provider::list_models_for_provider;
pub use provider::list_models_for_provider_blocking;
pub use provider::merge_custom_providers_into_config;
pub use provider::provider_endpoint;
pub use provider::resolve_provider;
pub use settings::CustomProvider;
pub use settings::DEFAULT_PROMPT_PATH;
pub use settings::DEFAULT_SEARCH_CONFIDENCE_MIN;
pub use settings::SETTINGS_PATH;
pub use settings::Settings;
pub use settings::global as global_settings;
pub use settings::init_global as init_global_settings;
pub use settings::load as load_settings;
pub use settings::persist as persist_settings;
pub use settings::persist_default_model_selection;
pub use settings::persist_search_confidence_min;
